package com.business.discovery.worker.scaffold;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;

/**
 * A deterministic, business-agnostic slice of the backend that is written to disk at scaffold
 * time instead of being generated by the LLM. Each module owns a fixed set of files (identified
 * by {@link #ownedFilePatterns()}) which ProjectPlanningNode strips from the LLM manifest, so
 * BackendGeneratorNode never regenerates over them and the shapes are correct by construction.
 *
 * <p>Add a new common slice (catalog, transaction, ...) by implementing this interface as a
 * Spring {@code @Component}: it is collected into the ordered list injected into
 * ProjectPlanningNode automatically — no plumbing changes required.
 */
public interface ScaffoldModule {

    /** Short identifier used in logs. */
    String name();

    /**
     * Writes this module's files under {@code backendJavaRoot} (the {@code backend/src/main/java}
     * directory), substituting {@code basePackage} (e.g. {@code "com.circuithouse"}) into each file.
     * Called only on the first attempt, before generation.
     */
    void write(Path backendJavaRoot, String basePackage) throws IOException;

    /**
     * Filename/path patterns this module owns. Any manifest FileSpec whose fileName or filePath
     * matches one of these is stripped before generation, so the LLM can never shadow a scaffolded
     * file — including under a renamed variant (JwtService for JwtUtil, SecurityConfiguration for
     * SecurityConfig, ...). Patterns are anchored to {@code .java} so frontend files are untouched.
     */
    List<Pattern> ownedFilePatterns();
}
