## Dev env database configurations.

server.port=8090


spring.application.name=discovery
spring.main.web-application-type=servlet

spring.datasource.url=jdbc:postgresql://localhost:5432/business_discovery
spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional but recommended
spring.jpa.open-in-view=false

# Model Identification
langchain4j.google-ai-gemini.chat-model.api-key=
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.5-pro

# Architectural Tuning (Phase 1)
langchain4j.google-ai-gemini.chat-model.temperature=0.2
langchain4j.google-ai-gemini.chat-model.top-p=0.95
langchain4j.google-ai-gemini.chat-model.max-output-tokens=4000

# Logging for Debugging (Optional but recommended for Phase 1)
langchain4j.google-ai-gemini.chat-model.log-requests=true
langchain4j.google-ai-gemini.chat-model.log-responses=true


# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

langchain4j.google-ai-gemini.embedding-model.model-name=gemini-embedding-001
