package com.business.discovery.worker.nodes;

import com.business.discovery.worker.constants.FailureType;
import com.business.discovery.worker.constants.FileType;
import com.business.discovery.worker.context.WorkerContext;
import com.business.discovery.worker.errorhandler.WorkerException;
import com.business.discovery.worker.model.GeneratedFile;
import com.business.discovery.worker.repository.GeneratedFileRepository;
import com.business.discovery.worker.service.BuildToolService;
import com.business.discovery.worker.service.llm.ArchitectureSpec;
import com.business.discovery.worker.service.llm.FeatureSpec;
import com.business.discovery.worker.service.llm.FileEntry;
import com.business.discovery.worker.service.llm.FileSpec;
import com.business.discovery.worker.service.llm.generator.LlmGeneratorService;
import com.business.discovery.worker.util.ArchitectureJsonUtil;
import com.business.discovery.worker.util.LayerOrderUtil;
import com.business.discovery.worker.util.TypeScriptExportRegistry;
import com.business.discovery.worker.util.TypeScriptImportChecker;
import com.business.discovery.worker.util.TypeScriptImportFixer;
import com.business.discovery.worker.service.GitService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.locks.ReentrantLock;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Component
@Order(8)
@Slf4j
public class FrontendGeneratorNode implements WorkerNode {

    // Max concurrent Flash LLM calls per layer — limits Gemini API rate pressure.
    private static final int MAX_PARALLEL_PER_LAYER = 5;

    // Canonical tsconfig.app.json — written when the LLM-generated one can't be patched.
    // noUnusedLocals/noUnusedParameters are false: LLM code has many transient unused
    // symbols and those tsc errors waste fix-LLM attempts on trivialities.
    // verbatimModuleSyntax is omitted (defaults false) so plain `import` works everywhere.
    private static final String CANONICAL_TSCONFIG_APP = """
            {
              "compilerOptions": {
                "target": "ES2020",
                "useDefineForClassFields": true,
                "lib": ["ES2020", "DOM", "DOM.Iterable"],
                "module": "ESNext",
                "skipLibCheck": true,
                "moduleResolution": "bundler",
                "allowImportingTsExtensions": true,
                "isolatedModules": true,
                "moduleDetection": "force",
                "noEmit": true,
                "jsx": "react-jsx",
                "strict": true,
                "noUnusedLocals": false,
                "noUnusedParameters": false,
                "noFallthroughCasesInSwitch": true,
                "paths": { "@/*": ["./src/*"] }
              },
              "include": ["src"]
            }
            """;

    // Canonical vite.config.ts — written at scaffold time and again at each ensureFrontendWorkspace call.
    private static final String CANONICAL_VITE_CONFIG = """
            import path from 'node:path'
            import { defineConfig } from 'vite'
            import react from '@vitejs/plugin-react'

            export default defineConfig({
              plugins: [react()],
              resolve: {
                alias: { '@': path.resolve(__dirname, './src') },
              },
              server: {
                proxy: {
                  '/api': {
                    target: 'http://localhost:8080',
                    changeOrigin: true,
                  },
                },
              },
              build: {
                outDir: 'dist',
              },
            })
            """;

    // Canonical root tsconfig.json — includes @/* paths so shadcn CLI can resolve component aliases.
    private static final String CANONICAL_TSCONFIG_ROOT = """
            {
              "files": [],
              "references": [
                { "path": "./tsconfig.app.json" },
                { "path": "./tsconfig.node.json" }
              ],
              "compilerOptions": {
                "baseUrl": ".",
                "paths": { "@/*": ["./src/*"] }
              }
            }
            """;

    // Minimal ESLint flat config used only for our --fix pass.
    // Ignores shadcn/ui components (generated by CLI, not by us).
    private static final String ESLINT_FIX_CONFIG = """
            import unusedImports from 'eslint-plugin-unused-imports';
            import tsParser from '@typescript-eslint/parser';

            export default [
              { ignores: ['dist', 'src/components/ui'] },
              {
                files: ['**/*.{ts,tsx}'],
                languageOptions: { parser: tsParser },
                plugins: { 'unused-imports': unusedImports },
                rules: {
                  'no-unused-vars': 'off',
                  'unused-imports/no-unused-imports': 'error',
                  'unused-imports/no-unused-vars': [
                    'warn',
                    { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' }
                  ],
                },
              },
            ];
            """;

    private final LlmGeneratorService flashLlm;
    private final BuildToolService buildToolService;
    private final GeneratedFileRepository fileRepo;
    private final GitService gitService;

    // Guards concurrent writes to ARCHITECTURE.json from parallel Flash LLM threads within a layer.
    private final ReentrantLock archJsonLock = new ReentrantLock();

    public FrontendGeneratorNode(@Qualifier("geminiFlash") LlmGeneratorService flashLlm,
                                 BuildToolService buildToolService,
                                 GeneratedFileRepository fileRepo,
                                 GitService gitService) {
        this.flashLlm = flashLlm;
        this.buildToolService = buildToolService;
        this.fileRepo = fileRepo;
        this.gitService = gitService;
    }

    @Override
    public void execute(WorkerContext ctx) {
        Path workspace = ctx.getWorkspaceDir();
        Path frontendDir = workspace.resolve("frontend");

        ArchitectureSpec architectureSpec = loadSpec(workspace);
        Map<String, FileSpec> specByPath = buildSpecByPath(architectureSpec);
        Map<String, FeatureSpec> featuresByName = buildFeaturesByName(architectureSpec);

        List<FileEntry> frontendFiles = ctx.getFileManifest().stream()
                .filter(e -> e.type() == FileType.FRONTEND)
                .sorted(Comparator.comparingInt(LayerOrderUtil::frontendPriority))
                .toList();

        log.info("[FrontendGeneratorNode] Processing {} frontend files in layer order", frontendFiles.size());

        if (frontendFiles.isEmpty()) {
            log.info("[FrontendGeneratorNode] No frontend files — skipping workspace setup");
            return;
        }

        // Full set of manifest paths — used by TypeScriptImportChecker to distinguish
        // "not generated yet" (pending) from "will never exist" (bad import).
        Set<String> manifestPaths = frontendFiles.stream()
                .map(FileEntry::path)
                .collect(Collectors.toSet());

        // Export registry built incrementally as layers complete — used by TypeScriptImportFixer.
        // Written sequentially (after each layer's parallel block) to avoid concurrent modification.
        TypeScriptExportRegistry exportRegistry = new TypeScriptExportRegistry(workspace);

        boolean requestedChangesMode = ctx.getBriefCtx().requestedChanges() != null
                && !ctx.getBriefCtx().requestedChanges().isBlank();

        if (!Files.exists(frontendDir.resolve("node_modules"))) {
            log.info("[FrontendGeneratorNode] node_modules missing — running npm install");
            BuildToolService.BuildResult install = buildToolService.runNpmInstall(frontendDir);
            if (!install.success()) {
                throw new WorkerException(FailureType.CODE,
                        "npm install failed before generation:\n" + install.output());
            }
            log.info("[FrontendGeneratorNode] npm install complete");
        }

        try {
            ensureFrontendWorkspace(frontendDir, workspace);

            // Ground-truth UI inventory: what @radix-ui packages and shadcn ui files ACTUALLY
            // export, enumerated from the installed workspace. Injected into every generation
            // prompt and consumed by UiImportRewriter — replaces hardcoded component knowledge.
            this.uiInventory = com.business.discovery.worker.util.UiComponentInventory.build(frontendDir);
            this.uiInventory.writeJson(workspace);
            log.info("[FrontendGeneratorNode] UI inventory: {} radix packages, {} shadcn ui files",
                    uiInventory.radixExports().size(), uiInventory.shadcnUiExports().size());

            // Group files by layer priority — within a layer, files don't depend on each other
            // and can be generated concurrently. TreeMap gives sorted layer iteration.
            TreeMap<Integer, List<FileEntry>> filesByLayer = frontendFiles.stream()
                    .collect(Collectors.groupingBy(LayerOrderUtil::frontendPriority,
                            TreeMap::new, Collectors.toList()));

            int filesProcessed = 0;

            for (Map.Entry<Integer, List<FileEntry>> layerEntry : filesByLayer.entrySet()) {
                List<FileEntry> layerFiles = layerEntry.getValue();
                String layerLabel = layerFiles.isEmpty() ? "?" : layerName(layerFiles.get(0));

                // Register skipped files' exports BEFORE parallel generation so TypeScriptImportFixer
                // can resolve imports from already-generated files in subsequent layers.
                for (FileEntry entry : layerFiles) {
                    FileSpec spec = specByPath.get(entry.path());
                    FeatureSpec feature = spec != null && spec.getFeatureName() != null
                            ? featuresByName.get(spec.getFeatureName()) : null;
                    Path filePath = workspace.resolve(entry.path());
                    if (shouldSkip(spec, feature, requestedChangesMode, Files.exists(filePath))) {
                        if (Files.exists(filePath)) {
                            exportRegistry.register(filePath, Files.readString(filePath));
                        }
                    }
                }

                List<FileEntry> toGenerate = layerFiles.stream()
                        .filter(e -> {
                            FileSpec spec = specByPath.get(e.path());
                            FeatureSpec feature = spec != null && spec.getFeatureName() != null
                                    ? featuresByName.get(spec.getFeatureName()) : null;
                            boolean exists = Files.exists(workspace.resolve(e.path()));
                            return !shouldSkip(spec, feature, requestedChangesMode, exists);
                        })
                        .toList();

                filesProcessed += layerFiles.size();

                if (toGenerate.isEmpty()) {
                    log.info("[FrontendGeneratorNode] Layer [{}] — all {} file(s) already done, skipping",
                            layerLabel, layerFiles.size());
                    continue;
                }

                int skipped = layerFiles.size() - toGenerate.size();
                log.info("[FrontendGeneratorNode] Layer [{}] — generating {} file(s) in parallel (skipping {})",
                        layerLabel, toGenerate.size(), skipped);

                int parallelism = Math.min(toGenerate.size(), MAX_PARALLEL_PER_LAYER);
                ExecutorService executor = Executors.newFixedThreadPool(parallelism);
                List<CompletableFuture<Void>> futures = toGenerate.stream()
                        .map(entry -> CompletableFuture.runAsync(() -> {
                            FileSpec spec = specByPath.get(entry.path());
                            FeatureSpec feature = spec != null && spec.getFeatureName() != null
                                    ? featuresByName.get(spec.getFeatureName()) : null;
                            Path filePath = workspace.resolve(entry.path());
                            String featureInstruction = feature != null ? feature.getFeatureInstruction() : null;
                            String fileRole = spec != null ? spec.getFileRole() : null;

                            if (featureInstruction == null || featureInstruction.isBlank()) {
                                log.warn("[FrontendGeneratorNode] No featureInstruction for '{}' (file: {}) — skipping",
                                        spec != null ? spec.getFeatureName() : "unknown", entry.path());
                                return;
                            }
                            try {
                                runGenerateStage(ctx, workspace, entry, filePath, spec,
                                        featureInstruction, fileRole, requestedChangesMode, feature,
                                        manifestPaths, exportRegistry);
                            } catch (IOException e) {
                                throw new UncheckedIOException(e);
                            }
                        }, executor))
                        .toList();

                try {
                    CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();
                } catch (CompletionException e) {
                    Throwable cause = e.getCause();
                    if (cause instanceof WorkerException we) throw we;
                    if (cause instanceof UncheckedIOException uioe) {
                        throw new WorkerException(FailureType.INFRA,
                                "File I/O error during frontend generation: " + uioe.getMessage(), uioe);
                    }
                    throw new WorkerException(FailureType.INFRA,
                            "Parallel generation failed in layer [" + layerLabel + "]: " + e.getMessage(), e);
                } finally {
                    executor.shutdownNow();
                }

                // Register newly generated files' exports after the parallel block so subsequent
                // layers can resolve imports from this layer (sequential, no concurrent access).
                for (FileEntry entry : toGenerate) {
                    Path filePath = workspace.resolve(entry.path());
                    if (Files.exists(filePath)) {
                        try {
                            exportRegistry.register(filePath, Files.readString(filePath));
                        } catch (IOException e) {
                            log.warn("[FrontendGeneratorNode] Could not register exports for {}: {}",
                                    entry.path(), e.getMessage());
                        }
                    }
                }

                // Checkpoint after each layer — work survives a container kill between layers
                gitService.commitAndPushCheckpoint(workspace,
                        "chore: frontend wip — " + layerLabel + " layer, " + filesProcessed
                                + " files (attempt " + ctx.getAttemptNumber() + ")",
                        ctx.getGithubBranch());
            }

            // Post-generation: scan all generated files for shadcn usage and run ESLint.
            // These must run after generation so LLM-generated imports are visible.
            try {
                ensureShadcnComponents(frontendDir, workspace);
            } catch (IOException e) {
                log.warn("[FrontendGeneratorNode] Post-generation shadcn scan failed: {}", e.getMessage());
            }
            runEslintPass(frontendDir);

        } catch (WorkerException e) {
            throw e;
        } catch (IOException e) {
            throw new WorkerException(FailureType.INFRA,
                    "Failed during frontend generation: " + e.getMessage(), e);
        }

        log.info("[FrontendGeneratorNode] Done — {} frontend files processed", frontendFiles.size());
    }

    // ── PLANNED → GENERATED ───────────────────────────────────────────────────

    // Set once per execute() before the parallel generation block; read-only afterwards.
    private volatile com.business.discovery.worker.util.UiComponentInventory uiInventory;

    private void runGenerateStage(WorkerContext ctx, Path workspace, FileEntry entry,
                                  Path filePath, FileSpec spec, String featureInstruction,
                                  String fileRole, boolean requestedChangesMode,
                                  FeatureSpec feature, Set<String> manifestPaths,
                                  TypeScriptExportRegistry exportRegistry) throws IOException {
        Map<String, String> depFiles = loadDependencyFiles(workspace, spec);
        if (uiInventory != null && !uiInventory.isEmpty()) {
            depFiles.put("AVAILABLE UI IMPORTS (ground truth — import ONLY names listed here)",
                    uiInventory.toPromptSection());
        }
        String existingContent = (requestedChangesMode && feature != null && feature.isChangeRequired())
                ? readIfExists(filePath) : null;

        String content = flashLlm.generateFileContent(entry.path(), featureInstruction,
                fileRole != null ? fileRole : "", depFiles, existingContent);
        Files.createDirectories(filePath.getParent());

        // Truncation guard: unbalanced braces means Flash hit its output token limit.
        // Skip the entire tsc fix loop — patching an incomplete file wastes LLM tokens.
        if (isBraceTruncated(content)) {
            log.warn("[FrontendGeneratorNode] Truncated output for {} — GENERATION_FAILED (saves fix-LLM calls)",
                    entry.path());
            Files.writeString(filePath, content);
            archJsonLock.lock();
            try {
                ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "GENERATION_FAILED");
            } finally {
                archJsonLock.unlock();
            }
            upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.GENERATION_FAILED);
            return;
        }

        Files.writeString(filePath, content);
        // Fix broken @/ and relative import paths using the export registry (zero LLM).
        // exportRegistry is read-only at this point — writes happen after the parallel block.
        TypeScriptImportFixer.fix(filePath, workspace, exportRegistry);
        // Types files must export every declaration — LLM often forgets 'export' on some of them.
        if (entry.path().contains("/types/")) {
            ensureAllTypesExported(filePath);
        }
        TypeScriptImportChecker.check(filePath, workspace, manifestPaths);

        archJsonLock.lock();
        try {
            ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "GENERATED");
        } finally {
            archJsonLock.unlock();
        }
        upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.GENERATED);
        // exportRegistry.register() is intentionally NOT called here — done after the parallel block
        // in execute() to avoid concurrent modification of the shared registry.
    }

    // ── Frontend workspace setup (runs once per attempt before generation) ────

    // Matches both canonical @/ alias and relative ../ui/ imports generated by LLMs
    private static final Pattern SHADCN_IMPORT =
            Pattern.compile("from\\s+['\"](?:@/components/ui|[./]+(?:components/)?ui)/([a-z][a-z0-9-]*)");

    // Parsed from `npx shadcn@latest search @shadcn` at first use — cached for the container lifetime.
    // null = not yet fetched. Empty set = fetch failed (fall back to allowing all).
    private static volatile java.util.Set<String> cachedValidShadcnComponents = null;
    private static final Pattern SHADCN_REGISTRY_LINE =
            Pattern.compile("^-\\s+@shadcn/([a-z][a-z0-9-]+)\\s+\\(ui\\)");
    // Deprecated components the CLI refuses to install — map to their replacement
    private static final Map<String, String> SHADCN_DEPRECATED = Map.of(
            "toast",     "sonner",
            "use-toast", "sonner"
    );

    private void ensureFrontendWorkspace(Path frontendDir, Path workspace) throws IOException {
        writeCanonicalConfigs(frontendDir);
        ensureTailwind(frontendDir);
        ensureHookformResolvers(frontendDir);
        ensureRadixUiPackages(frontendDir);
        ensureShadcnComponents(frontendDir, workspace);
        ensureEslintSetup(frontendDir);
        runEslintPass(frontendDir);
    }

    private void writeCanonicalConfigs(Path frontendDir) throws IOException {
        Path viteConfig = frontendDir.resolve("vite.config.ts");
        if (Files.exists(viteConfig)) {
            Files.writeString(viteConfig, CANONICAL_VITE_CONFIG);
            log.info("[FrontendGeneratorNode] Wrote canonical vite.config.ts");
        }
        Path tsconfigApp = frontendDir.resolve("tsconfig.app.json");
        if (Files.exists(tsconfigApp)) {
            Files.writeString(tsconfigApp, CANONICAL_TSCONFIG_APP);
            log.info("[FrontendGeneratorNode] Wrote canonical tsconfig.app.json");
        }
        Path tsconfigRoot = frontendDir.resolve("tsconfig.json");
        if (Files.exists(tsconfigRoot)) {
            Files.writeString(tsconfigRoot, CANONICAL_TSCONFIG_ROOT);
            log.info("[FrontendGeneratorNode] Wrote canonical tsconfig.json");
        }
        // vite-env.d.ts — declares CSS/SVG/PNG module types so tsc accepts Vite asset imports.
        Path srcDir = frontendDir.resolve("src");
        Files.createDirectories(srcDir);
        Files.writeString(srcDir.resolve("vite-env.d.ts"), "/// <reference types=\"vite/client\" />\n");
        log.info("[FrontendGeneratorNode] Wrote src/vite-env.d.ts");

        // App.tsx — clean shell with no Vite demo imports.
        Path appTsx = srcDir.resolve("App.tsx");
        Files.writeString(appTsx, CANONICAL_APP_TSX);
        log.info("[FrontendGeneratorNode] Wrote canonical App.tsx");

        Path mainTsx = srcDir.resolve("main.tsx");
        Files.writeString(mainTsx, CANONICAL_MAIN_TSX);
        log.info("[FrontendGeneratorNode] Wrote canonical main.tsx");
    }

    private static final String CANONICAL_APP_TSX = """
            import './index.css'

            export default function App() {
              return <div />
            }
            """;

    private static final String CANONICAL_MAIN_TSX = """
            import { StrictMode } from 'react'
            import { createRoot } from 'react-dom/client'
            import './index.css'
            import App from './App'

            createRoot(document.getElementById('root')!).render(
              <StrictMode>
                <App />
              </StrictMode>
            )
            """;

    private static final String POSTCSS_CONFIG = """
            export default {
              plugins: {
                tailwindcss: {},
                autoprefixer: {},
              },
            }
            """;

    private static final String TAILWIND_CONFIG = """
            import type { Config } from "tailwindcss"
            const config: Config = {
              darkMode: ["class"],
              content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
              theme: {
                extend: {
                  colors: {
                    border: "hsl(var(--border))",
                    input: "hsl(var(--input))",
                    ring: "hsl(var(--ring))",
                    background: "hsl(var(--background))",
                    foreground: "hsl(var(--foreground))",
                    primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
                    secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
                    destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
                    muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
                    accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
                    popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
                    card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
                  },
                  borderRadius: {
                    lg: "var(--radius)",
                    md: "calc(var(--radius) - 2px)",
                    sm: "calc(var(--radius) - 4px)",
                  },
                },
              },
              plugins: [],
            }
            export default config
            """;

    private static final String TAILWIND_INDEX_CSS = """
            @tailwind base;
            @tailwind components;
            @tailwind utilities;

            @layer base {
              :root {
                --background: 0 0% 100%;
                --foreground: 222.2 47.4% 11.2%;
                --card: 0 0% 100%;
                --card-foreground: 222.2 47.4% 11.2%;
                --popover: 0 0% 100%;
                --popover-foreground: 222.2 47.4% 11.2%;
                --primary: 222.2 47.4% 11.2%;
                --primary-foreground: 210 40% 98%;
                --secondary: 210 40% 96.1%;
                --secondary-foreground: 222.2 47.4% 11.2%;
                --muted: 210 40% 96.1%;
                --muted-foreground: 215.4 16.3% 46.9%;
                --accent: 210 40% 96.1%;
                --accent-foreground: 222.2 47.4% 11.2%;
                --destructive: 0 100% 50%;
                --destructive-foreground: 210 40% 98%;
                --border: 214.3 31.8% 91.4%;
                --input: 214.3 31.8% 91.4%;
                --ring: 215 20.2% 65.1%;
                --radius: 0.5rem;
              }
              .dark {
                --background: 224 71% 4%;
                --foreground: 213 31% 91%;
                --card: 224 71% 4%;
                --card-foreground: 213 31% 91%;
                --popover: 224 71% 4%;
                --popover-foreground: 215 20.2% 65.1%;
                --primary: 210 40% 98%;
                --primary-foreground: 222.2 47.4% 1.2%;
                --secondary: 222.2 47.4% 11.2%;
                --secondary-foreground: 210 40% 98%;
                --muted: 223 47% 11%;
                --muted-foreground: 215.4 16.3% 56.9%;
                --accent: 216 34% 17%;
                --accent-foreground: 210 40% 98%;
                --destructive: 0 63% 31%;
                --destructive-foreground: 210 40% 98%;
                --border: 216 34% 17%;
                --input: 216 34% 17%;
                --ring: 216 34% 17%;
              }
            }

            @layer base {
              * { @apply border-border; }
              body { @apply bg-background text-foreground; margin: 0; }
            }
            """;

    private void ensureTailwind(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (!Files.exists(pkgPath)) return;

        if (!Files.readString(pkgPath).contains("\"tailwindcss\"")) {
            log.info("[FrontendGeneratorNode] Installing tailwindcss v3 + postcss + autoprefixer");
            BuildToolService.BuildResult r = buildToolService.runNpmInstallDevPackages(
                    frontendDir, "tailwindcss@^3.4.1", "postcss@^8.4.33", "autoprefixer@^10.4.17");
            if (r.success()) log.info("[FrontendGeneratorNode] Tailwind stack installed");
            else log.warn("[FrontendGeneratorNode] Tailwind install failed (exit={}): {}", r.exitCode(), r.output());
        } else {
            log.info("[FrontendGeneratorNode] tailwindcss already present");
        }

        Path postcssConfig = frontendDir.resolve("postcss.config.js");
        if (!Files.exists(postcssConfig)) {
            Files.writeString(postcssConfig, POSTCSS_CONFIG);
            log.info("[FrontendGeneratorNode] Wrote postcss.config.js");
        }

        Path tailwindConfig = frontendDir.resolve("tailwind.config.ts");
        if (!Files.exists(tailwindConfig)) {
            Files.writeString(tailwindConfig, TAILWIND_CONFIG);
            log.info("[FrontendGeneratorNode] Wrote tailwind.config.ts");
        }

        Path indexCss = frontendDir.resolve("src/index.css");
        if (!Files.exists(indexCss) || !Files.readString(indexCss).contains("@tailwind")) {
            Files.writeString(indexCss, TAILWIND_INDEX_CSS);
            log.info("[FrontendGeneratorNode] Wrote src/index.css with Tailwind directives + shadcn CSS variables");
        }
    }

    private void ensureHookformResolvers(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (!Files.exists(pkgPath)) return;
        if (Files.readString(pkgPath).contains("@hookform/resolvers")) {
            log.info("[FrontendGeneratorNode] @hookform/resolvers already in package.json");
            return;
        }
        log.info("[FrontendGeneratorNode] Installing @hookform/resolvers (always required)");
        BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(
                frontendDir, "@hookform/resolvers");
        if (r.success()) log.info("[FrontendGeneratorNode] Installed @hookform/resolvers");
        else log.warn("[FrontendGeneratorNode] @hookform/resolvers install failed: {}", r.output());
    }

    private static final List<String> RADIX_CORE_PACKAGES = List.of(
            "@radix-ui/react-select", "@radix-ui/react-dialog",
            "@radix-ui/react-label", "@radix-ui/react-checkbox",
            "@radix-ui/react-alert-dialog", "clsx"
    );

    private void ensureRadixUiPackages(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (!Files.exists(pkgPath)) return;
        String pkgJson = Files.readString(pkgPath);
        List<String> missing = RADIX_CORE_PACKAGES.stream()
                .filter(pkg -> !pkgJson.contains("\"" + pkg + "\""))
                .toList();
        if (missing.isEmpty()) {
            log.info("[FrontendGeneratorNode] All Radix UI core packages present");
            return;
        }
        log.info("[FrontendGeneratorNode] Installing missing Radix UI packages: {}", missing);
        for (String pkg : missing) {
            BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(frontendDir, pkg);
            if (r.success()) log.info("[FrontendGeneratorNode] Installed {}", pkg);
            else log.warn("[FrontendGeneratorNode] Failed to install {} (exit={}): {}", pkg, r.exitCode(), r.output());
        }
    }

    private void ensureShadcnComponents(Path frontendDir, Path workspace) throws IOException {
        Set<String> needed = detectShadcnComponents(workspace);
        if (needed.isEmpty()) return;

        Path uiDir = frontendDir.resolve("src/components/ui");
        Set<String> missing = needed.stream()
                .filter(c -> !Files.exists(uiDir.resolve(c + ".tsx")))
                .collect(Collectors.toCollection(TreeSet::new));
        if (missing.isEmpty()) {
            log.info("[FrontendGeneratorNode] All shadcn components already present");
            return;
        }

        log.info("[FrontendGeneratorNode] shadcn components needed: {}", missing);

        Path componentsJson = frontendDir.resolve("components.json");
        boolean needsComponentsJson = !Files.exists(componentsJson)
                || Files.readString(componentsJson).contains("tailwind.config.js");
        if (needsComponentsJson) {
            Files.writeString(componentsJson, """
                    {
                      "$schema": "https://ui.shadcn.com/schema.json",
                      "style": "default",
                      "rsc": false,
                      "tsx": true,
                      "tailwind": {
                        "config": "",
                        "css": "src/index.css",
                        "baseColor": "slate",
                        "cssVariables": true,
                        "prefix": ""
                      },
                      "aliases": {
                        "components": "@/components",
                        "utils": "@/lib/utils",
                        "ui": "@/components/ui",
                        "lib": "@/lib",
                        "hooks": "@/hooks"
                      },
                      "iconLibrary": "lucide"
                    }
                    """);
            log.info("[FrontendGeneratorNode] Wrote components.json for shadcn (Tailwind v4 compatible)");
        }

        ensureRootTsconfigPaths(frontendDir);

        BuildToolService.BuildResult result = buildToolService.runShadcnAdd(frontendDir, missing);
        if (result.success()) {
            log.info("[FrontendGeneratorNode] shadcn add succeeded for: {}\nOutput:\n{}", missing, result.output());
        } else {
            log.warn("[FrontendGeneratorNode] shadcn add failed (exit={}) for: {}\nOutput:\n{}",
                    result.exitCode(), missing, result.output());
        }

        ensureLibUtils(frontendDir);
    }

    private void ensureRootTsconfigPaths(Path frontendDir) throws IOException {
        Path rootTsconfig = frontendDir.resolve("tsconfig.json");
        if (!Files.exists(rootTsconfig)) return;
        String content = Files.readString(rootTsconfig);
        if (content.contains("\"paths\"")) {
            log.info("[FrontendGeneratorNode] tsconfig.json already has @/* paths");
            return;
        }
        Files.writeString(rootTsconfig, CANONICAL_TSCONFIG_ROOT);
        log.info("[FrontendGeneratorNode] Re-wrote tsconfig.json with canonical template (paths were missing)");
    }

    private static final String LIB_UTILS_CONTENT = """
            import { clsx, type ClassValue } from "clsx"
            import { twMerge } from "tailwind-merge"

            export function cn(...inputs: ClassValue[]) {
              return twMerge(clsx(inputs))
            }
            """;

    private void ensureLibUtils(Path frontendDir) throws IOException {
        Path libDir = frontendDir.resolve("src/lib");
        Path utilsFile = libDir.resolve("utils.ts");
        if (Files.exists(utilsFile)) {
            log.info("[FrontendGeneratorNode] src/lib/utils.ts already present");
            return;
        }
        for (String pkg : List.of("clsx", "tailwind-merge", "class-variance-authority")) {
            String pkgJson = Files.readString(frontendDir.resolve("package.json"));
            if (!pkgJson.contains("\"" + pkg + "\"")) {
                BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(frontendDir, pkg);
                if (r.success()) log.info("[FrontendGeneratorNode] Installed {}", pkg);
                else log.warn("[FrontendGeneratorNode] Failed to install {} (exit={}): {}", pkg, r.exitCode(), r.output());
            }
        }
        Files.createDirectories(libDir);
        Files.writeString(utilsFile, LIB_UTILS_CONTENT);
        log.info("[FrontendGeneratorNode] Created src/lib/utils.ts");
    }

    private void ensureEslintSetup(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (Files.exists(pkgPath) && !Files.readString(pkgPath).contains("eslint-plugin-unused-imports")) {
            log.info("[FrontendGeneratorNode] Installing eslint-plugin-unused-imports + @typescript-eslint/parser");
            BuildToolService.BuildResult r = buildToolService.runNpmInstallDevPackages(
                    frontendDir, "eslint-plugin-unused-imports", "@typescript-eslint/parser", "@typescript-eslint/eslint-plugin");
            if (r.success()) {
                log.info("[FrontendGeneratorNode] Installed eslint-plugin-unused-imports + typescript-eslint");
            } else {
                log.warn("[FrontendGeneratorNode] eslint-plugin-unused-imports install failed (exit={}):\n{}",
                        r.exitCode(), r.output());
            }
        }

        Path fixConfig = frontendDir.resolve("eslint.fix.config.mjs");
        Files.writeString(fixConfig, ESLINT_FIX_CONFIG);
        log.info("[FrontendGeneratorNode] Wrote eslint.fix.config.mjs");
    }

    private void runEslintPass(Path frontendDir) {
        BuildToolService.BuildResult result = buildToolService.runEslintFix(frontendDir);
        if (result.exitCode() == 2) {
            log.warn("[FrontendGeneratorNode] eslint --fix crashed (exit=2) — skipping auto-fix pass:\n{}",
                    result.output());
        } else if (result.output().isBlank()) {
            log.info("[FrontendGeneratorNode] eslint --fix: no auto-fixable issues");
        } else {
            log.info("[FrontendGeneratorNode] eslint --fix (exit={}) — applied fixes:\n{}",
                    result.exitCode(), result.output());
        }
    }

    private Set<String> detectShadcnComponents(Path workspace) {
        Path srcDir = workspace.resolve("frontend/src");
        if (!Files.exists(srcDir)) return Set.of();

        Set<String> validRegistry = getValidShadcnComponents(workspace.resolve("frontend"));
        Set<String> components = new TreeSet<>();
        Set<String> skipped = new TreeSet<>();

        try (var stream = Files.walk(srcDir)) {
            stream.filter(p -> p.toString().endsWith(".ts") || p.toString().endsWith(".tsx"))
                    .forEach(p -> {
                        try {
                            Matcher m = SHADCN_IMPORT.matcher(Files.readString(p));
                            while (m.find()) {
                                String name = m.group(1);
                                // Replace deprecated component names with their successors
                                if (SHADCN_DEPRECATED.containsKey(name)) {
                                    components.add(SHADCN_DEPRECATED.get(name));
                                    continue;
                                }
                                // Validate against live registry — skip hallucinated names
                                if (validRegistry.isEmpty() || validRegistry.contains(name)) {
                                    components.add(name); // empty = fetch failed, allow all
                                } else {
                                    skipped.add(name);
                                }
                            }
                        } catch (IOException ignored) {}
                    });
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not scan for shadcn components: {}", e.getMessage());
        }
        if (!skipped.isEmpty()) {
            log.warn("[FrontendGeneratorNode] Skipped non-registry shadcn imports (not in @shadcn registry): {}", skipped);
        }
        return components;
    }

    /**
     * Runs `npx shadcn@latest search @shadcn` and parses the (ui) component lines.
     * Result is cached for the container lifetime — the registry doesn't change mid-run.
     * Retries up to 3 times on failure. Falls back to empty set (= allow all) if all
     * attempts fail (e.g. network unavailable inside the container).
     */
    private Set<String> getValidShadcnComponents(Path frontendDir) {
        if (cachedValidShadcnComponents != null) return cachedValidShadcnComponents;
        synchronized (FrontendGeneratorNode.class) {
            if (cachedValidShadcnComponents != null) return cachedValidShadcnComponents;

            int maxAttempts = 3;
            for (int attempt = 1; attempt <= maxAttempts; attempt++) {
                try {
                    ProcessBuilder pb = new ProcessBuilder("npx", "shadcn@latest", "search", "@shadcn")
                            .directory(frontendDir.toFile())
                            .redirectErrorStream(true);
                    Process proc = pb.start();
                    String output = new String(proc.getInputStream().readAllBytes());
                    proc.waitFor();

                    Set<String> valid = new java.util.LinkedHashSet<>();
                    for (String line : output.split("\n")) {
                        Matcher m = SHADCN_REGISTRY_LINE.matcher(line.trim());
                        if (m.find()) valid.add(m.group(1));
                    }

                    if (valid.isEmpty()) {
                        log.warn("[FrontendGeneratorNode] shadcn registry fetch attempt {}/{} returned no (ui) components — retrying",
                                attempt, maxAttempts);
                        continue;
                    }

                    log.info("[FrontendGeneratorNode] Fetched {} valid shadcn components from live registry (attempt {})",
                            valid.size(), attempt);
                    cachedValidShadcnComponents = valid;
                    return cachedValidShadcnComponents;

                } catch (Exception e) {
                    log.warn("[FrontendGeneratorNode] shadcn registry fetch attempt {}/{} failed: {}",
                            attempt, maxAttempts, e.getMessage());
                }
            }

            log.warn("[FrontendGeneratorNode] All {} shadcn registry fetch attempts failed — allowing all components", maxAttempts);
            cachedValidShadcnComponents = Set.of(); // empty = allow all
            return cachedValidShadcnComponents;
        }
    }

    // ── shouldSkip ────────────────────────────────────────────────────────────

    private boolean shouldSkip(FileSpec spec, FeatureSpec feature, boolean requestedChangesMode,
                               boolean existsOnDisk) {
        if (spec == null) return false;
        if (requestedChangesMode) return feature == null || !feature.isChangeRequired();
        String status = spec.getStatus();
        // GENERATION_FAILED is NOT skipped — falls through to runGenerateStage for a fresh attempt.
        // GENERATED + present on disk IS skipped: after generation the fix loop owns the
        // file. Regenerating on retry destroyed the previous attempt's ErrorFixAgent
        // patches (Sisyphus loop, multifit-aundh 2026-07-04) — retries never converged.
        return "SPEC_COMPLIANT".equalsIgnoreCase(status)
                || "VALIDATED".equalsIgnoreCase(status)
                || ("GENERATED".equalsIgnoreCase(status) && existsOnDisk);
    }

    // ── Spec loading ──────────────────────────────────────────────────────────

    private ArchitectureSpec loadSpec(Path workspace) {
        if (!ArchitectureJsonUtil.exists(workspace)) return new ArchitectureSpec();
        try {
            return ArchitectureJsonUtil.read(workspace);
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not load spec: {}", e.getMessage());
            return new ArchitectureSpec();
        }
    }

    private Map<String, FileSpec> buildSpecByPath(ArchitectureSpec spec) {
        if (spec.getFiles() == null) return Map.of();
        return spec.getFiles().stream()
                .filter(f -> f.getFilePath() != null)
                .collect(Collectors.toMap(FileSpec::getFilePath, f -> f, (a, b) -> a));
    }

    private Map<String, FeatureSpec> buildFeaturesByName(ArchitectureSpec spec) {
        if (spec.getFeatures() == null) return Map.of();
        return spec.getFeatures().stream()
                .filter(f -> f.getFeatureName() != null)
                .collect(Collectors.toMap(FeatureSpec::getFeatureName, f -> f, (a, b) -> a));
    }

    private Map<String, String> loadDependencyFiles(Path workspace, FileSpec spec) {
        java.util.LinkedHashMap<String, String> deps = new java.util.LinkedHashMap<>();
        if (spec == null) return deps;

        List<String> depPaths = spec.getImportsFrom();
        if (depPaths == null || depPaths.isEmpty()) depPaths = spec.getDependsOn();
        if (depPaths == null) return deps;

        for (String depPath : depPaths) {
            Path file = workspace.resolve(depPath);
            if (Files.exists(file)) {
                try {
                    deps.put(depPath, Files.readString(file));
                } catch (IOException ignored) {}
            }
        }
        return deps;
    }

    // Matches interface/type/enum/class declarations that are NOT already exported.
    private static final Pattern UNEXPORTED_DECL =
            Pattern.compile("^(interface|type|enum|class)\\s", Pattern.MULTILINE);

    private void ensureAllTypesExported(Path filePath) throws IOException {
        String content = Files.readString(filePath);
        String fixed = UNEXPORTED_DECL.matcher(content).replaceAll("export $1 ");
        if (!fixed.equals(content)) {
            Files.writeString(filePath, fixed);
            log.info("[FrontendGeneratorNode] Ensured exports on declarations in {}", filePath.getFileName());
        }
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    private String readIfExists(Path filePath) {
        if (!Files.exists(filePath)) return null;
        try {
            return Files.readString(filePath);
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not read {}: {}", filePath, e.getMessage());
            return null;
        }
    }

    private String layerName(FileEntry entry) {
        return LayerOrderUtil.frontendLayerName(entry);
    }

    // Open-brace count > close-brace count means the LLM stopped mid-output (token limit hit).
    private static boolean isBraceTruncated(String content) {
        if (content == null || content.isBlank()) return true;
        int depth = 0;
        for (char c : content.toCharArray()) {
            if (c == '{') depth++;
            else if (c == '}') depth--;
        }
        return depth > 0;
    }

    // ── DB record ─────────────────────────────────────────────────────────────

    private void upsertRecord(WorkerContext ctx, String filePath,
                              GeneratedFile.FileType fileType, GeneratedFile.FileStatus status) {
        fileRepo.findByTaskIdAndFilePath(ctx.getTaskId(), filePath).ifPresentOrElse(
                existing -> {
                    existing.setStatus(status);
                    existing.setAttemptNumber(ctx.getAttemptNumber());
                    if (status != GeneratedFile.FileStatus.GENERATION_FAILED) {
                        existing.setErrorMessage(null);
                    }
                    fileRepo.save(existing);
                },
                () -> fileRepo.save(GeneratedFile.builder()
                        .taskId(ctx.getTaskId())
                        .filePath(filePath)
                        .fileType(fileType)
                        .status(status)
                        .attemptNumber(ctx.getAttemptNumber())
                        .build())
        );
    }
}
