package com.business.discovery.worker.nodes;

import com.business.discovery.worker.constants.FailureType;
import com.business.discovery.worker.constants.FileType;
import com.business.discovery.worker.context.WorkerContext;
import com.business.discovery.worker.errorhandler.WorkerException;
import com.business.discovery.worker.model.GeneratedFile;
import com.business.discovery.worker.repository.GeneratedFileRepository;
import com.business.discovery.worker.service.BuildToolService;
import com.business.discovery.worker.service.llm.ArchitectureSpec;
import com.business.discovery.worker.service.llm.ComplianceResult;
import com.business.discovery.worker.service.llm.FeatureSpec;
import com.business.discovery.worker.service.llm.FileEntry;
import com.business.discovery.worker.service.llm.FileSpec;
import com.business.discovery.worker.service.llm.generator.LlmGeneratorService;
import com.business.discovery.worker.util.ArchitectureJsonUtil;
import com.business.discovery.worker.util.LayerOrderUtil;
import com.business.discovery.worker.util.WorkspaceReader;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Component
@Order(8)
@Slf4j
public class FrontendGeneratorNode implements WorkerNode {

    private static final int MAX_COMPILE_FIX_ATTEMPTS = 3;
    private static final int MAX_SPEC_FIX_ROUNDS = 2;

    // Canonical tsconfig.app.json — written when the LLM-generated one can't be patched.
    // noUnusedLocals/noUnusedParameters are false: LLM code has many transient unused
    // symbols and those tsc errors waste fix-LLM attempts on trivialities.
    // verbatimModuleSyntax is omitted (defaults false) so plain `import` works everywhere.
    private static final String CANONICAL_TSCONFIG_APP = """
            {
              "compilerOptions": {
                "target": "ES2020",
                "useDefineForClassFields": true,
                "lib": ["ES2020", "DOM", "DOM.Iterable"],
                "module": "ESNext",
                "skipLibCheck": true,
                "moduleResolution": "bundler",
                "allowImportingTsExtensions": true,
                "isolatedModules": true,
                "moduleDetection": "force",
                "noEmit": true,
                "jsx": "react-jsx",
                "strict": true,
                "noUnusedLocals": false,
                "noUnusedParameters": false,
                "noFallthroughCasesInSwitch": true,
                "paths": { "@/*": ["./src/*"] }
              },
              "include": ["src"]
            }
            """;

    // Minimal ESLint flat config used only for our --fix pass.
    // Ignores shadcn/ui components (generated by CLI, not by us).
    // Removes entire unused import lines (plugin handles what tsc TS6133 cannot auto-fix).
    private static final String ESLINT_FIX_CONFIG = """
            import unusedImports from 'eslint-plugin-unused-imports';
            import tsParser from '@typescript-eslint/parser';

            export default [
              { ignores: ['dist', 'src/components/ui'] },
              {
                files: ['**/*.{ts,tsx}'],
                languageOptions: { parser: tsParser },
                plugins: { 'unused-imports': unusedImports },
                rules: {
                  'no-unused-vars': 'off',
                  'unused-imports/no-unused-imports': 'error',
                  'unused-imports/no-unused-vars': [
                    'warn',
                    { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' }
                  ],
                },
              },
            ];
            """;

    private final LlmGeneratorService flashLlm;
    private final LlmGeneratorService proLlm;
    private final LlmGeneratorService fixLlm;
    private final BuildToolService buildToolService;
    private final GeneratedFileRepository fileRepo;

    public FrontendGeneratorNode(@Qualifier("geminiFlash") LlmGeneratorService flashLlm,
                                 @Qualifier("geminiPro") LlmGeneratorService proLlm,
                                 @Qualifier("geminiFlash") LlmGeneratorService fixLlm,
                                 BuildToolService buildToolService,
                                 GeneratedFileRepository fileRepo) {
        this.flashLlm = flashLlm;
        this.proLlm = proLlm;
        this.fixLlm = fixLlm;
        this.buildToolService = buildToolService;
        this.fileRepo = fileRepo;
    }

    @Override
    public void execute(WorkerContext ctx) {
        Path workspace = ctx.getWorkspaceDir();
        Path frontendDir = workspace.resolve("frontend");

        ArchitectureSpec architectureSpec = loadSpec(workspace);
        Map<String, FileSpec> specByPath = buildSpecByPath(architectureSpec);
        Map<String, FeatureSpec> featuresByName = buildFeaturesByName(architectureSpec);

        List<FileEntry> frontendFiles = ctx.getFileManifest().stream()
                .filter(e -> e.type() == FileType.FRONTEND)
                .sorted(Comparator.comparingInt(LayerOrderUtil::frontendPriority))
                .toList();

        log.info("[FrontendGeneratorNode] Processing {} frontend files in layer order", frontendFiles.size());

        if (frontendFiles.isEmpty()) {
            log.info("[FrontendGeneratorNode] No frontend files — skipping workspace setup");
            return;
        }

        boolean requestedChangesMode = ctx.getBriefCtx().requestedChanges() != null
                && !ctx.getBriefCtx().requestedChanges().isBlank();

        if (!Files.exists(frontendDir.resolve("node_modules"))) {
            log.info("[FrontendGeneratorNode] node_modules missing — running npm install");
            BuildToolService.BuildResult install = buildToolService.runNpmInstall(frontendDir);
            if (!install.success()) {
                throw new WorkerException(FailureType.CODE,
                        "npm install failed before tsc checks:\n" + install.output());
            }
            log.info("[FrontendGeneratorNode] npm install complete");
        }

        try {
            ensureFrontendWorkspace(frontendDir, workspace);

            for (FileEntry entry : frontendFiles) {
                FileSpec spec = specByPath.get(entry.path());
                FeatureSpec feature = spec != null && spec.getFeatureName() != null
                        ? featuresByName.get(spec.getFeatureName()) : null;
                Path filePath = workspace.resolve(entry.path());

                if (shouldSkip(spec, feature, requestedChangesMode)) {
                    log.info("[FrontendGeneratorNode] Skipping [{}]: {}", layerName(entry), entry.path());
                    continue;
                }

                String featureInstruction = feature != null ? feature.getFeatureInstruction() : null;
                String fileRole = spec != null ? spec.getFileRole() : null;
                if (featureInstruction == null || featureInstruction.isBlank()) {
                    log.warn("[FrontendGeneratorNode] No featureInstruction for '{}' (file: {}) — skipping",
                            spec != null ? spec.getFeatureName() : "unknown", entry.path());
                    continue;
                }

                String status = spec != null ? spec.getStatus() : "PLANNED";

                // Stage 3: PLANNED → GENERATED
                // GENERATION_FAILED is also regenerated from scratch — never skip it permanently.
                boolean needsGeneration = "PLANNED".equalsIgnoreCase(status)
                        || "GENERATION_FAILED".equalsIgnoreCase(status)
                        || (requestedChangesMode && feature != null && feature.isChangeRequired());
                if (needsGeneration) {
                    log.info("[FrontendGeneratorNode] Stage 3 — generating [{}]: {}", layerName(entry), entry.path());
                    status = runGenerateStage(ctx, workspace, entry, filePath, spec,
                            featureInstruction, fileRole, requestedChangesMode, feature);
                }

                // Stage 1: GENERATED → VALIDATED
                if ("GENERATED".equalsIgnoreCase(status)) {
                    log.info("[FrontendGeneratorNode] Stage 1 — tsc check [{}]: {}", layerName(entry), entry.path());
                    status = runTscStage(ctx, workspace, frontendDir, entry, filePath, spec, specByPath);
                }

                // Stage 2: VALIDATED → SPEC_COMPLIANT
                if ("VALIDATED".equalsIgnoreCase(status)) {
                    log.info("[FrontendGeneratorNode] Stage 2 — spec check [{}]: {}", layerName(entry), entry.path());
                    runSpecCheckStage(ctx, workspace, frontendDir, entry, filePath, spec,
                            featureInstruction, fileRole, specByPath);
                }
            }
        } catch (WorkerException e) {
            throw e;
        } catch (IOException e) {
            throw new WorkerException(FailureType.INFRA,
                    "Failed during frontend generation: " + e.getMessage(), e);
        }

        log.info("[FrontendGeneratorNode] Done — {} frontend files processed", frontendFiles.size());
    }

    // ── Stage 3: PLANNED → GENERATED ─────────────────────────────────────────

    private String runGenerateStage(WorkerContext ctx, Path workspace, FileEntry entry,
                                    Path filePath, FileSpec spec, String featureInstruction,
                                    String fileRole, boolean requestedChangesMode,
                                    FeatureSpec feature) throws IOException {
        Map<String, String> depFiles = loadDependencyFiles(workspace, spec);
        String existingContent = (requestedChangesMode && feature != null && feature.isChangeRequired())
                ? readIfExists(filePath) : null;

        String content = flashLlm.generateFileContent(entry.path(), featureInstruction,
                fileRole != null ? fileRole : "", depFiles, existingContent);
        Files.createDirectories(filePath.getParent());
        Files.writeString(filePath, content);

        ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "GENERATED");
        upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.GENERATED);
        return "GENERATED";
    }

    // ── Stage 1: GENERATED → VALIDATED ───────────────────────────────────────

    private String runTscStage(WorkerContext ctx, Path workspace, Path frontendDir,
                               FileEntry entry, Path filePath,
                               FileSpec spec, Map<String, FileSpec> specByPath) throws IOException {
        WorkspaceReader reader = new WorkspaceReader(workspace);
        String lastTscOutput = "";
        for (int attempt = 0; attempt <= MAX_COMPILE_FIX_ATTEMPTS; attempt++) {
            BuildToolService.BuildResult result = buildToolService.runTscCheck(frontendDir);
            lastTscOutput = result.output();
            if (result.success()) {
                ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "VALIDATED");
                upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.VALIDATED);
                log.info("[FrontendGeneratorNode] tsc OK: {}", entry.path());
                return "VALIDATED";
            }

            if (attempt < MAX_COMPILE_FIX_ATTEMPTS) {
                List<String> toFix = parseFailingFiles(result.output(), workspace);
                if (toFix.isEmpty()) toFix = List.of(entry.path());

                log.warn("[FrontendGeneratorNode] tsc failed (attempt {}/{}) — fixing {} file(s): {}\ntsc output:\n{}",
                        attempt + 1, MAX_COMPILE_FIX_ATTEMPTS, toFix.size(), toFix, result.output());

                for (String failingPath : toFix) {
                    if (!reader.exists(failingPath)) continue;
                    FileSpec failingSpec = specByPath.get(failingPath);
                    String triggerFilePath = failingPath.equals(entry.path()) ? null : entry.path();
                    Map<String, String> fixCtx = buildFixContext(reader, failingSpec, failingPath, triggerFilePath, workspace);
                    String content = reader.readFile(failingPath);
                    String fixed = fixLlm.fixFileContent(failingPath, content, result.output(), fixCtx);
                    if (looksLikeCode(fixed, failingPath)) {
                        log.info("[FrontendGeneratorNode] fix-LLM patched {} ({} bytes)", failingPath, fixed.length());
                        Files.writeString(workspace.resolve(failingPath), fixed);
                    } else {
                        log.warn("[FrontendGeneratorNode] fix-LLM returned prose for {} — original file preserved. Prose preview: {}",
                                failingPath, fixed.substring(0, Math.min(300, fixed.length())).replace("\n", " "));
                    }
                }
                // After fix-LLM writes, run eslint to auto-remove unused imports and
                // other mechanical issues before the next tsc attempt.
                log.info("[FrontendGeneratorNode] Running eslint --fix after fix-LLM pass (attempt {})", attempt + 1);
                runEslintPass(frontendDir);
            }
        }

        log.error("[FrontendGeneratorNode] tsc still failing for {} after {} attempts — GENERATION_FAILED\nFinal tsc output:\n{}",
                entry.path(), MAX_COMPILE_FIX_ATTEMPTS, lastTscOutput);
        ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "GENERATION_FAILED");
        upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.GENERATION_FAILED);
        return "GENERATION_FAILED";
    }

    // ── Stage 2: VALIDATED → SPEC_COMPLIANT ──────────────────────────────────

    private void runSpecCheckStage(WorkerContext ctx, Path workspace, Path frontendDir,
                                   FileEntry entry, Path filePath, FileSpec spec,
                                   String featureInstruction, String fileRole,
                                   Map<String, FileSpec> specByPath) throws IOException {
        // Combine fileRole + featureInstruction so the compliance check has full per-file context
        String combinedSpec = "FILE ROLE: " + (fileRole != null ? fileRole : "")
                + "\n\nFEATURE INSTRUCTION:\n" + featureInstruction;

        for (int round = 0; round < MAX_SPEC_FIX_ROUNDS; round++) {
            String fileContent = Files.readString(filePath);
            ComplianceResult compliance = proLlm.checkSpecCompliance(entry.path(), fileContent, combinedSpec);

            if (compliance.compliant()) {
                ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "SPEC_COMPLIANT");
                upsertRecord(ctx, entry.path(), GeneratedFile.FileType.FRONTEND, GeneratedFile.FileStatus.SPEC_COMPLIANT);
                log.info("[FrontendGeneratorNode] Spec compliant: {}", entry.path());
                return;
            }

            log.warn("[FrontendGeneratorNode] Spec drift for {} (round {}/{}) — issues: {}",
                    entry.path(), round + 1, MAX_SPEC_FIX_ROUNDS, compliance.issues());

            if (round == MAX_SPEC_FIX_ROUNDS - 1) {
                log.warn("[FrontendGeneratorNode] Max spec-fix rounds exhausted for {} — leaving as VALIDATED",
                        entry.path());
                return;
            }

            // Keep featureInstruction intact; append corrections to fileRole only
            String correctedRole = (fileRole != null ? fileRole : "")
                    + "\n\nFix these spec deviations:\n- "
                    + String.join("\n- ", compliance.issues());
            Map<String, String> depFiles = loadDependencyFiles(workspace, spec);
            String corrected = flashLlm.generateFileContent(entry.path(), featureInstruction, correctedRole, depFiles, null);
            Files.writeString(filePath, corrected);
            ArchitectureJsonUtil.updateFileStatus(workspace, entry.path(), "GENERATED");

            // Re-run Stage 1 on the corrected file
            String newStatus = runTscStage(ctx, workspace, frontendDir, entry, filePath, spec, specByPath);
            if (!"VALIDATED".equalsIgnoreCase(newStatus)) return; // GENERATION_FAILED — stop
        }
    }

    // ── Frontend workspace setup (runs once per attempt before generation) ────

    private static final Pattern SHADCN_IMPORT =
            Pattern.compile("from\\s+['\"]@/components/ui/([a-z][a-z0-9-]*)");

    private void ensureFrontendWorkspace(Path frontendDir, Path workspace) throws IOException {
        patchViteConfig(frontendDir);
        patchTsconfigPaths(frontendDir);
        ensureHookformResolvers(frontendDir);
        ensureRadixUiPackages(frontendDir);
        ensureShadcnComponents(frontendDir, workspace);
        ensureEslintSetup(frontendDir);
        runEslintPass(frontendDir);
    }

    private void patchViteConfig(Path frontendDir) throws IOException {
        Path configPath = frontendDir.resolve("vite.config.ts");
        if (!Files.exists(configPath)) return;
        String content = Files.readString(configPath);
        if (content.contains("'@'") || content.contains("\"@\"")) {
            log.info("[FrontendGeneratorNode] vite.config.ts already has @/ alias");
            return;
        }
        String patched = "import path from 'node:path'\n"
                + "import { defineConfig } from 'vite'\n"
                + "import react from '@vitejs/plugin-react'\n\n"
                + "export default defineConfig({\n"
                + "  plugins: [react()],\n"
                + "  resolve: {\n"
                + "    alias: { '@': path.resolve(__dirname, './src') },\n"
                + "  },\n"
                + "})\n";
        Files.writeString(configPath, patched);
        log.info("[FrontendGeneratorNode] Patched vite.config.ts with @/ alias");
    }

    private void patchTsconfigPaths(Path frontendDir) throws IOException {
        Path configPath = frontendDir.resolve("tsconfig.app.json");
        if (!Files.exists(configPath)) return;
        String content = Files.readString(configPath);
        boolean changed = false;

        // Always strip verbatimModuleSyntax — LLM adds it habitually; causes TS1484 on generated code.
        // Must run before the paths check: LLM often writes both keys in the same file.
        String stripped = content.replaceAll("\\n[ \\t]*\"verbatimModuleSyntax\"\\s*:\\s*true,?", "");
        if (!stripped.equals(content)) {
            content = stripped;
            changed = true;
            log.info("[FrontendGeneratorNode] Stripped verbatimModuleSyntax from tsconfig.app.json");
        }

        if (content.contains("\"paths\"")) {
            if (changed) Files.writeString(configPath, content);
            log.info("[FrontendGeneratorNode] tsconfig.app.json already has paths");
            return;
        }

        // Inject paths before noFallthroughCasesInSwitch (standard Vite scaffold position)
        String patched = content.replaceFirst(
                "\"noFallthroughCasesInSwitch\"(\\s*:\\s*true)",
                "\"paths\": { \"@/*\": [\"./src/*\"] },\n    \"noFallthroughCasesInSwitch\"$1");
        if (!patched.equals(content)) {
            Files.writeString(configPath, patched);
            log.info("[FrontendGeneratorNode] Patched tsconfig.app.json with @/* paths");
            return;
        }
        // LLM generated a non-standard tsconfig — replace entirely with canonical version
        log.warn("[FrontendGeneratorNode] tsconfig.app.json patch failed (noFallthroughCasesInSwitch not found) — writing canonical tsconfig");
        Files.writeString(configPath, CANONICAL_TSCONFIG_APP);
    }

    private void ensureHookformResolvers(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (!Files.exists(pkgPath)) return;
        if (Files.readString(pkgPath).contains("@hookform/resolvers")) {
            log.info("[FrontendGeneratorNode] @hookform/resolvers already in package.json");
            return;
        }
        log.info("[FrontendGeneratorNode] Installing @hookform/resolvers (always required)");
        BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(
                frontendDir, "@hookform/resolvers");
        if (r.success()) log.info("[FrontendGeneratorNode] Installed @hookform/resolvers");
        else log.warn("[FrontendGeneratorNode] @hookform/resolvers install failed: {}", r.output());
    }

    private static final List<String> RADIX_CORE_PACKAGES = List.of(
            "@radix-ui/react-select", "@radix-ui/react-dialog",
            "@radix-ui/react-label", "@radix-ui/react-checkbox",
            "@radix-ui/react-alert-dialog", "clsx"
    );

    private void ensureRadixUiPackages(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (!Files.exists(pkgPath)) return;
        String pkgJson = Files.readString(pkgPath);
        List<String> missing = RADIX_CORE_PACKAGES.stream()
                .filter(pkg -> !pkgJson.contains("\"" + pkg + "\""))
                .toList();
        if (missing.isEmpty()) {
            log.info("[FrontendGeneratorNode] All Radix UI core packages present");
            return;
        }
        log.info("[FrontendGeneratorNode] Installing missing Radix UI packages: {}", missing);
        for (String pkg : missing) {
            BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(frontendDir, pkg);
            if (r.success()) log.info("[FrontendGeneratorNode] Installed {}", pkg);
            else log.warn("[FrontendGeneratorNode] Failed to install {} (exit={}): {}", pkg, r.exitCode(), r.output());
        }
    }

    private void ensureShadcnComponents(Path frontendDir, Path workspace) throws IOException {
        Set<String> needed = detectShadcnComponents(workspace);
        if (needed.isEmpty()) return;

        Path uiDir = frontendDir.resolve("src/components/ui");
        Set<String> missing = needed.stream()
                .filter(c -> !Files.exists(uiDir.resolve(c + ".tsx")))
                .collect(Collectors.toCollection(TreeSet::new));
        if (missing.isEmpty()) {
            log.info("[FrontendGeneratorNode] All shadcn components already present");
            return;
        }

        log.info("[FrontendGeneratorNode] shadcn components needed: {}", missing);

        // Write components.json if not present, or fix it if it references tailwind.config.js
        // (wrong for Tailwind v4 — shadcn add silently skips all components when this is set).
        Path componentsJson = frontendDir.resolve("components.json");
        boolean needsComponentsJson = !Files.exists(componentsJson)
                || Files.readString(componentsJson).contains("tailwind.config.js");
        if (needsComponentsJson) {
            Files.writeString(componentsJson, """
                    {
                      "$schema": "https://ui.shadcn.com/schema.json",
                      "style": "default",
                      "rsc": false,
                      "tsx": true,
                      "tailwind": {
                        "config": "",
                        "css": "src/index.css",
                        "baseColor": "slate",
                        "cssVariables": true,
                        "prefix": ""
                      },
                      "aliases": {
                        "components": "@/components",
                        "utils": "@/lib/utils",
                        "ui": "@/components/ui",
                        "lib": "@/lib",
                        "hooks": "@/hooks"
                      },
                      "iconLibrary": "lucide"
                    }
                    """);
            log.info("[FrontendGeneratorNode] Wrote components.json for shadcn (Tailwind v4 compatible)");
        }

        // shadcn CLI resolves @/ via tsconfig.json (root) compilerOptions.paths, not tsconfig.app.json.
        // Patch root tsconfig.json to add paths if not present.
        ensureRootTsconfigPaths(frontendDir);

        BuildToolService.BuildResult result = buildToolService.runShadcnAdd(frontendDir, missing);
        if (result.success()) {
            log.info("[FrontendGeneratorNode] shadcn add succeeded for: {}\nOutput:\n{}", missing, result.output());
        } else {
            log.warn("[FrontendGeneratorNode] shadcn add failed (exit={}) for: {}\nOutput:\n{}",
                    result.exitCode(), missing, result.output());
        }

        // shadcn components all import cn from @/lib/utils — create it and install its deps.
        ensureLibUtils(frontendDir);
    }

    private void ensureRootTsconfigPaths(Path frontendDir) throws IOException {
        Path rootTsconfig = frontendDir.resolve("tsconfig.json");
        if (!Files.exists(rootTsconfig)) return;
        String content = Files.readString(rootTsconfig);
        if (content.contains("\"paths\"")) {
            log.info("[FrontendGeneratorNode] tsconfig.json already has paths");
            return;
        }
        // Inject compilerOptions with @/ paths so shadcn CLI can resolve component locations.
        String patched = content.replace(
                "\"files\": []",
                "\"files\": [],\n  \"compilerOptions\": { \"baseUrl\": \".\", \"paths\": { \"@/*\": [\"./src/*\"] } }");
        if (!patched.equals(content)) {
            Files.writeString(rootTsconfig, patched);
            log.info("[FrontendGeneratorNode] Patched tsconfig.json with @/* paths for shadcn CLI");
        }
    }

    private static final String LIB_UTILS_CONTENT = """
            import { clsx, type ClassValue } from "clsx"
            import { twMerge } from "tailwind-merge"

            export function cn(...inputs: ClassValue[]) {
              return twMerge(clsx(inputs))
            }
            """;

    private void ensureLibUtils(Path frontendDir) throws IOException {
        Path libDir = frontendDir.resolve("src/lib");
        Path utilsFile = libDir.resolve("utils.ts");
        if (Files.exists(utilsFile)) {
            log.info("[FrontendGeneratorNode] src/lib/utils.ts already present");
            return;
        }
        // Install deps first — shadcn components import from both packages.
        for (String pkg : List.of("clsx", "tailwind-merge", "class-variance-authority")) {
            String pkgJson = Files.readString(frontendDir.resolve("package.json"));
            if (!pkgJson.contains("\"" + pkg + "\"")) {
                BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(frontendDir, pkg);
                if (r.success()) log.info("[FrontendGeneratorNode] Installed {}", pkg);
                else log.warn("[FrontendGeneratorNode] Failed to install {} (exit={}): {}", pkg, r.exitCode(), r.output());
            }
        }
        Files.createDirectories(libDir);
        Files.writeString(utilsFile, LIB_UTILS_CONTENT);
        log.info("[FrontendGeneratorNode] Created src/lib/utils.ts");
    }

    private void ensureEslintSetup(Path frontendDir) throws IOException {
        Path pkgPath = frontendDir.resolve("package.json");
        if (Files.exists(pkgPath) && !Files.readString(pkgPath).contains("eslint-plugin-unused-imports")) {
            log.info("[FrontendGeneratorNode] Installing eslint-plugin-unused-imports");
            BuildToolService.BuildResult r = buildToolService.runNpmInstallPackage(
                    frontendDir, "eslint-plugin-unused-imports");
            if (r.success()) {
                log.info("[FrontendGeneratorNode] Installed eslint-plugin-unused-imports");
            } else {
                log.warn("[FrontendGeneratorNode] eslint-plugin-unused-imports install failed (exit={}):\n{}",
                        r.exitCode(), r.output());
            }
        }

        // Always overwrite — ensures the worker's canonical config is used even on reruns.
        Path fixConfig = frontendDir.resolve("eslint.fix.config.mjs");
        Files.writeString(fixConfig, ESLINT_FIX_CONFIG);
        log.info("[FrontendGeneratorNode] Wrote eslint.fix.config.mjs");
    }

    private void runEslintPass(Path frontendDir) {
        BuildToolService.BuildResult result = buildToolService.runEslintFix(frontendDir);
        if (result.exitCode() == 2) {
            // Exit 2 = eslint itself crashed (bad config, missing plugin)
            log.warn("[FrontendGeneratorNode] eslint --fix crashed (exit=2) — skipping auto-fix pass:\n{}",
                    result.output());
        } else if (result.output().isBlank()) {
            log.info("[FrontendGeneratorNode] eslint --fix: no auto-fixable issues");
        } else {
            // Exit 1 = unfixable issues remain — that's expected, we just want the fixes applied
            log.info("[FrontendGeneratorNode] eslint --fix (exit={}) — applied fixes:\n{}",
                    result.exitCode(), result.output());
        }
    }

    private Set<String> detectShadcnComponents(Path workspace) {
        Path srcDir = workspace.resolve("frontend/src");
        if (!Files.exists(srcDir)) return Set.of();
        Set<String> components = new TreeSet<>();
        try (var stream = Files.walk(srcDir)) {
            stream.filter(p -> p.toString().endsWith(".ts") || p.toString().endsWith(".tsx"))
                    .forEach(p -> {
                        try {
                            Matcher m = SHADCN_IMPORT.matcher(Files.readString(p));
                            while (m.find()) components.add(m.group(1));
                        } catch (IOException ignored) {}
                    });
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not scan for shadcn components: {}", e.getMessage());
        }
        return components;
    }

    // ── shouldSkip ────────────────────────────────────────────────────────────

    private boolean shouldSkip(FileSpec spec, FeatureSpec feature, boolean requestedChangesMode) {
        if (spec == null) return false;
        if (requestedChangesMode) return feature == null || !feature.isChangeRequired();
        String status = spec.getStatus();
        // GENERATION_FAILED is NOT skipped — falls through to needsGeneration for a fresh attempt.
        return "SPEC_COMPLIANT".equalsIgnoreCase(status);
    }

    // ── Spec loading ──────────────────────────────────────────────────────────

    private ArchitectureSpec loadSpec(Path workspace) {
        if (!ArchitectureJsonUtil.exists(workspace)) return new ArchitectureSpec();
        try {
            return ArchitectureJsonUtil.read(workspace);
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not load spec: {}", e.getMessage());
            return new ArchitectureSpec();
        }
    }

    private Map<String, FileSpec> buildSpecByPath(ArchitectureSpec spec) {
        if (spec.getFiles() == null) return Map.of();
        return spec.getFiles().stream()
                .filter(f -> f.getFilePath() != null)
                .collect(Collectors.toMap(FileSpec::getFilePath, f -> f, (a, b) -> a));
    }

    private Map<String, FeatureSpec> buildFeaturesByName(ArchitectureSpec spec) {
        if (spec.getFeatures() == null) return Map.of();
        return spec.getFeatures().stream()
                .filter(f -> f.getFeatureName() != null)
                .collect(Collectors.toMap(FeatureSpec::getFeatureName, f -> f, (a, b) -> a));
    }

    private Map<String, String> loadDependencyFiles(Path workspace, FileSpec spec) {
        Map<String, String> deps = new LinkedHashMap<>();
        if (spec == null) return deps;

        List<String> depPaths = spec.getImportsFrom();
        if (depPaths == null || depPaths.isEmpty()) depPaths = spec.getDependsOn();
        if (depPaths == null) return deps;

        for (String depPath : depPaths) {
            Path file = workspace.resolve(depPath);
            if (Files.exists(file)) {
                try {
                    deps.put(depPath, Files.readString(file));
                } catch (IOException ignored) {}
            }
        }
        return deps;
    }

    // tsc error lines (tsconfig.app.json, run from frontendDir):
    //   src/context/AuthContext.tsx(1,1): error TS1434: ...
    private static final Pattern TSC_ERROR_PATH =
            Pattern.compile("(src/\\S+\\.tsx?)\\(\\d+,\\d+\\)");

    // TypeScript import specifier: from './foo' | from '../bar' | from '@/types/auth'
    private static final Pattern TS_IMPORT_PATTERN =
            Pattern.compile("from\\s+['\"]([^'\"]+)['\"]", Pattern.MULTILINE);

    private List<String> parseFailingFiles(String output, Path workspace) {
        LinkedHashSet<String> paths = new LinkedHashSet<>();
        Matcher m = TSC_ERROR_PATH.matcher(output);
        while (m.find() && paths.size() < 3) {
            String rel = "frontend/" + m.group(1);
            if (Files.exists(workspace.resolve(rel))) paths.add(rel);
        }
        return new ArrayList<>(paths);
    }

    /**
     * Builds the fix context from four sources:
     * 1. Dep files declared in the failing file's spec (imports_from / depends_on)
     * 2. Auto-resolved imports: parse actual `from '...'` statements in the failing file
     *    and load the matching workspace files — so the fix-LLM always sees the real type
     *    definitions, even when the spec's importsFrom list is incomplete.
     * 3. tsconfig.json + package.json — compiler settings and installed packages
     * 4. triggerFilePath — the file we just wrote that caused the other file to break
     *    (null when the failing file IS the current file)
     */
    private Map<String, String> buildFixContext(WorkspaceReader reader, FileSpec spec,
                                                String failingPath, String triggerFilePath,
                                                Path workspace) {
        Map<String, String> ctx = new LinkedHashMap<>();
        if (spec != null) {
            List<String> deps = spec.getImportsFrom();
            if (deps == null || deps.isEmpty()) deps = spec.getDependsOn();
            if (deps != null) deps.forEach(dep -> addIfFound(ctx, reader, dep));
        }
        resolveTypeScriptImports(ctx, reader, failingPath, workspace);
        if (triggerFilePath != null) resolveTypeScriptImports(ctx, reader, triggerFilePath, workspace);
        addIfFound(ctx, reader, "frontend/tsconfig.json");
        addIfFound(ctx, reader, "frontend/package.json");
        if (triggerFilePath != null) addIfFound(ctx, reader, triggerFilePath);
        return ctx;
    }

    /**
     * Parses `from '...'` statements in a TypeScript file and loads the referenced
     * workspace files into ctx. Handles relative imports (./foo, ../bar) and the
     * @/ alias (maps to frontend/src/). Skips node_modules imports.
     */
    private void resolveTypeScriptImports(Map<String, String> ctx, WorkspaceReader reader,
                                           String filePath, Path workspace) {
        String content = reader.readFile(filePath);
        if (content.startsWith("FILE_NOT_FOUND:")) return;
        Path fileDir = workspace.resolve(filePath).getParent();
        Matcher m = TS_IMPORT_PATTERN.matcher(content);
        while (m.find()) {
            String specifier = m.group(1);
            String base;
            if (specifier.startsWith("./") || specifier.startsWith("../")) {
                base = workspace.relativize(fileDir.resolve(specifier).normalize()).toString();
            } else if (specifier.startsWith("@/")) {
                base = "frontend/src/" + specifier.substring(2);
            } else {
                continue; // node_modules import — skip
            }
            for (String ext : List.of("", ".ts", ".tsx", "/index.ts", "/index.tsx")) {
                String candidate = base + ext;
                if (!ctx.containsKey(candidate)) {
                    addIfFound(ctx, reader, candidate);
                    if (ctx.containsKey(candidate)) break;
                }
            }
        }
    }

    /**
     * Returns false when the fix-LLM returned a prose explanation instead of code.
     * Prose starts with natural-language words; TypeScript files must start with a
     * recognised code token. Prevents corrupted files from ever reaching disk.
     */
    private boolean looksLikeCode(String content, String filePath) {
        if (content == null || content.isBlank()) return false;
        String firstToken = content.stripLeading().split("[\\s({]")[0];
        if (filePath.endsWith(".ts") || filePath.endsWith(".tsx")) {
            return firstToken.matches(
                    "import|export|const|let|var|function|class|interface|type|enum|//|/\\*|<!--|@");
        }
        if (filePath.endsWith(".java")) {
            return firstToken.matches("package|import|//|/\\*|@|public|private|protected|class|enum|record");
        }
        return true;
    }

    private void addIfFound(Map<String, String> ctx, WorkspaceReader reader, String path) {
        String content = reader.readFile(path);
        if (!content.startsWith("FILE_NOT_FOUND:")) ctx.put(path, content);
    }

    private String readIfExists(Path filePath) {
        if (!Files.exists(filePath)) return null;
        try {
            return Files.readString(filePath);
        } catch (IOException e) {
            log.warn("[FrontendGeneratorNode] Could not read {}: {}", filePath, e.getMessage());
            return null;
        }
    }

    private String layerName(FileEntry entry) {
        return LayerOrderUtil.frontendLayerName(entry);
    }

    private void upsertRecord(WorkerContext ctx, String filePath,
                              GeneratedFile.FileType fileType, GeneratedFile.FileStatus status) {
        fileRepo.findByTaskIdAndFilePath(ctx.getTaskId(), filePath).ifPresentOrElse(
                existing -> {
                    existing.setStatus(status);
                    existing.setAttemptNumber(ctx.getAttemptNumber());
                    if (status != GeneratedFile.FileStatus.GENERATION_FAILED) {
                        existing.setErrorMessage(null);
                    }
                    fileRepo.save(existing);
                },
                () -> fileRepo.save(GeneratedFile.builder()
                        .taskId(ctx.getTaskId())
                        .filePath(filePath)
                        .fileType(fileType)
                        .status(status)
                        .attemptNumber(ctx.getAttemptNumber())
                        .build())
        );
    }
}
