package com.business.discovery.worker.nodes;

import com.business.discovery.worker.context.WorkerContext;
import com.business.discovery.worker.model.ArchitectBrief;
import com.business.discovery.worker.model.BusinessEntity;
import com.business.discovery.worker.repository.ContainerTaskRepository;
import com.business.discovery.worker.service.GitHubApiService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.stream.Collectors;

@Component
@Order(18)
@Slf4j
@RequiredArgsConstructor
public class PullRequestNode implements WorkerNode {

    private final GitHubApiService gitHubApiService;
    private final ContainerTaskRepository taskRepo;

    @Override
    public void execute(WorkerContext ctx) {
        String repoName = extractRepoName(ctx.getGithubRepoUrl());
        String branch = ctx.getGithubBranch();
        String title = "feat: " + ctx.getBusiness().getTitle() + " website";
        String body = buildPrBody(ctx);

        String prUrl = gitHubApiService.createPullRequest(repoName, branch, title, body);

        ctx.setGithubPrUrl(prUrl);
        taskRepo.updateGithubPrUrl(ctx.getTaskId(), prUrl);

        // Master monitors container logs for this line to extract the PR URL
        log.info("PR_URL={}", prUrl);
        log.info("[PullRequestNode] PR created/found: {}", prUrl);
    }

    private String buildPrBody(WorkerContext ctx) {
        BusinessEntity business = ctx.getBusiness();
        ArchitectBrief brief = ctx.getBrief();

        String features = brief.getMustHaveFeatures() != null && !brief.getMustHaveFeatures().isEmpty()
                ? brief.getMustHaveFeatures().stream().map(f -> "- " + f).collect(Collectors.joining("\n"))
                : "- Core business website features";

        String techStack = brief.getRecommendedTechStack() != null
                ? brief.getRecommendedTechStack().entrySet().stream()
                        .map(e -> "- **" + e.getKey() + "**: " + e.getValue())
                        .collect(Collectors.joining("\n"))
                : "- Spring Boot 3 + React 19 + PostgreSQL";

        String smokeSection = ctx.getSmokeTestedImage() != null
                ? "### Verification\n✅ Smoke-tested — boot, frontend, and API-with-data gates passed.\n"
                  + "📦 Image: `" + ctx.getSmokeTestedImage() + "`\n"
                : "### Verification\n⚠️ Smoke test skipped or image not published for this attempt.\n";

        return """
                ## %s Website

                Auto-generated website for **%s** — %s, %s.

                ### Must-Have Features
                %s

                ### Tech Stack
                %s

                %s
                ---
                Generated by Discovery Worker | Attempt %d | Brief ID: %s
                """.formatted(
                business.getTitle(),
                business.getTitle(),
                nullSafe(business.getCategory(), "Local Business"),
                nullSafe(brief.getLocation(), "India"),
                features,
                techStack,
                smokeSection,
                ctx.getAttemptNumber(),
                ctx.getBriefId());
    }

    private String extractRepoName(String repoUrl) {
        return repoUrl.substring(repoUrl.lastIndexOf('/') + 1)
                .replace(".git", "");
    }

    private String nullSafe(String value, String fallback) {
        return (value != null && !value.isBlank()) ? value : fallback;
    }
}
