package com.business.discovery.worker.util;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit coverage for the import-catalog renderer that seeds the frontend generation prompt with a
 * closed-world list of already-generated modules, so Flash imports what exists instead of inventing
 * modules the fixer must repair.
 */
class TypeScriptExportRegistryTest {

    private final Path workspace = Path.of("/ws");

    @Test
    void emptyRegistryRendersBlankAndReportsEmpty() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);

        assertThat(reg.isEmpty()).isTrue();
        assertThat(reg.toImportCatalog()).isEmpty();
    }

    @Test
    void groupsSymbolsByModuleUnderAliasSortedDeterministically() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/context/AuthContext.tsx"),
                "export const AuthProvider = () => null;\nexport function useAuth() { return null; }");
        reg.register(workspace.resolve("frontend/src/services/bookingService.ts"),
                "export function getBookings() {}\nexport function createBooking() {}");
        reg.register(workspace.resolve("frontend/src/types/local/booking.ts"),
                "export interface BookingState { id: string; }");

        assertThat(reg.isEmpty()).isFalse();
        // Modules sorted by alias; symbols sorted within each module; @/ alias applied; no trailing newline.
        assertThat(reg.toImportCatalog()).isEqualTo(
                "@/context/AuthContext -> AuthProvider, useAuth\n"
                + "@/services/bookingService -> createBooking, getBookings\n"
                + "@/types/local/booking -> BookingState");
    }

    @Test
    void leavesPathWithoutFrontendSrcPrefixUnaliased() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("shared/thing.ts"), "export type Thing = string;");

        assertThat(reg.toImportCatalog()).isEqualTo("shared/thing -> Thing");
    }

    @Test
    void includesReExportedSymbols() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/components/index.ts"),
                "export { Card, Modal } from './ui';");

        assertThat(reg.toImportCatalog()).isEqualTo("@/components/index -> Card, Modal");
    }

    @Test
    void capturesDefaultVsNamedBinding() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/shell/AdminLayout.tsx"),
                "export default function AdminLayout() { return null; }");
        reg.register(workspace.resolve("frontend/src/components/ui/badge.tsx"),
                "export const Badge = () => null;");

        assertThat(reg.resolveBinding("AdminLayout")).contains(TypeScriptExportRegistry.Binding.DEFAULT);
        assertThat(reg.resolveBinding("Badge")).contains(TypeScriptExportRegistry.Binding.NAMED);
        assertThat(reg.resolveBinding("Nonexistent")).isEmpty();
    }

    @Test
    void reExportedSymbolsAreNamedBinding() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/components/index.ts"),
                "export { Card } from './ui';");

        assertThat(reg.resolveBinding("Card")).contains(TypeScriptExportRegistry.Binding.NAMED);
    }

    // ── Mechanical hook files (now governed by the registry for referencing) ────────────────────

    /** The real FrontendHookGenerator output shape — the registry must index every useX as a NAMED export. */
    private static final String CLASS_HOOKS = """
            // GENERATED from the backend API contract — do not edit by hand.
            // One TanStack hook per service function — generated by FrontendHookGenerator.

            import { useMutation, useQueryClient } from '@tanstack/react-query';
            import { createGymClass, updateGymClass, deleteGymClass } from '@/services/classService';
            import type { GymClassDto } from '@/types/gym';

            export function useCreateGymClass(): { mutate: (vars: GymClassDto) => void; isPending: boolean } {
              return {} as never;
            }
            export function useUpdateGymClass(): { mutate: (vars: { classId: number; request: GymClassDto }) => void } {
              return {} as never;
            }
            export function useDeleteGymClass(): { mutate: (vars: number) => void } {
              return {} as never;
            }
            """;

    @Test
    void indexesMechanicalHookFileExportsOnly() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/hooks/classHooks.ts"), CLASS_HOOKS);

        // Only the three exported hooks — never the imported symbols (createGymClass etc.).
        assertThat(reg.toImportCatalog()).isEqualTo(
                "@/hooks/classHooks -> useCreateGymClass, useDeleteGymClass, useUpdateGymClass");
        assertThat(reg.knows("createGymClass")).isFalse();   // an import, not an export
    }

    @Test
    void resolvesHookSpecifierAndBindingForTheFixer() {
        TypeScriptExportRegistry reg = new TypeScriptExportRegistry(workspace);
        reg.register(workspace.resolve("frontend/src/hooks/classHooks.ts"), CLASS_HOOKS);

        // resolveSpecifier feeds TypeScriptImportFixer: symbol → workspace-relative path (no extension).
        assertThat(reg.resolveSpecifier("useUpdateGymClass")).contains("frontend/src/hooks/classHooks");
        assertThat(reg.resolveBinding("useUpdateGymClass")).contains(TypeScriptExportRegistry.Binding.NAMED);
        assertThat(reg.knows("useUpdateGymClass")).isTrue();
        assertThat(reg.resolveSpecifier("useNonexistent")).isEmpty();
    }

    // ── buildFromDisk (the seed step that indexes hooks + services + types at frontend-gen start) ──

    @Test
    void buildFromDiskWalksTreeAndIndexesEverything(@TempDir Path ws) throws Exception {
        write(ws, "frontend/src/hooks/classHooks.ts", CLASS_HOOKS);
        write(ws, "frontend/src/services/classService.ts",
                "export const createGymClass = async () => {};\nexport const getAllGymClasses = async () => {};");
        write(ws, "frontend/src/pages/ClassesPage.tsx", "export default function ClassesPage() { return null; }");

        TypeScriptExportRegistry reg =
                TypeScriptExportRegistry.buildFromDisk(ws.resolve("frontend/src"), ws);

        assertThat(reg.toImportCatalog()).isEqualTo(
                "@/hooks/classHooks -> useCreateGymClass, useDeleteGymClass, useUpdateGymClass\n"
                + "@/pages/ClassesPage -> ClassesPage\n"
                + "@/services/classService -> createGymClass, getAllGymClasses");
        assertThat(reg.resolveBinding("ClassesPage")).contains(TypeScriptExportRegistry.Binding.DEFAULT);
        assertThat(reg.resolveBinding("useCreateGymClass")).contains(TypeScriptExportRegistry.Binding.NAMED);
    }

    private static void write(Path ws, String rel, String content) throws Exception {
        Path p = ws.resolve(rel);
        Files.createDirectories(p.getParent());
        Files.writeString(p, content);
    }
}
